@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana


Class Main{
+static void main(String[] args)
}


Class RoleMaster{}

Class Rules{}
Class Dice{}

package views{
Class StartMenuView{}
Class CharacterSheetView{}
Class CharacterInfoView{}
Class SkillListView{}
Class SpellListView{}
Class InventoryView{}
Class TalentsAndFlawsView{}
Class MovementView{}
Class PrimaryStatsView{}
Class WeaponAttackSetupView{}
Class DefenseView{}
Class MagicItemsView{}
Class GeneralEquipmentView{}
}
CharacterSheetView *-- CharacterInfoView
CharacterSheetView *-- PrimaryStatsView
CharacterSheetView *-- MovementView
CharacterSheetView *-- WeaponAttackSetupView
CharacterSheetView *-- DefenseView
InventoryView o-- MagicItemsView
InventoryView o-- GeneralEquipmentView


package models{
    Class CharacterSheet{
        - int level;
        - int xp
        - String name
        - String background;
        # Culture culture;
        # Race race;
        # Profession profession;
        # PrimaryStats stats;
        # Defense defense;
        # ManeuversMovementAndEncumbrance MME;
        # Inventory inventory;
        # Map SkillList <String, Skill>;
        # Map SpellList <String, Spell>;
        # Set <TalentsAndFlaws> TalentsAndFlaws;
    }
    Class GeneralEquipment{}
    Class Skill{
    -boolean proffesionalSkill
    -String name
    -String specialization
    -int cultureRanks
    -String stats
    -int statBonus
    -int totalRanks
    -int rankBonus
    -int proffesionalBonus
    -int knack
    -int totalBonus
    -boolean firstRankBought
    -boolean secondRankBought
    }
    Class SkillCategory{
        #String name
        #String[] stats
        #int DPCostFirst
        #int DPCostSecond
        #Map<String,Skill> skillList
        #String getName()
        #String[] getStats()
        #int getDPcostFirst()
        #int getDPcostSedond()
        #Map<String, Skill> getSkills()
        #void addSkill()
    }
    Class Spell{
        -list<String>category<>
        -boolean proffesionalSkill
        -String name
        -String specialization
        -int cultureRanks
        -String stats
        -int statBonus
        -int totalRanks
        -int rankBonus
        -int proffesionalBonus
        -int knack
        -int totalBonus
        -boolean firstRankBought
        -boolean secondRankBought
    }
    Class SpellCategory{
        -String name
        -String stats
        -int statBonus
        -int DPCostFirst
        -int DPCostSecond
    }
    Class Inventory{}
    Class MME{
        # Map<String,Pace> paces
        # Map<String,double> featsOfStrength
        # String size
        # double wtAllowance
        # double carried
        # double encPenalty
        # double maxPace
        # double totalManeuverPenalty
        # double bmr
        # int initiative
        # int hitPoints
        # int endurance
        # int power
    }
    Class Pace {
        # String name
        # double prRound
        # double prPhase
        # String penaltyAp
        # String loadLimit
    }
    Class PrimaryStats{}
    Class Defense{}
    Class MagicItems{}
    Class Race{
    - String race
    - int bonusDps;
    - int agility;
    - int constitution;
    - int empathy;
    - int intuition;
    - int memory;
    - int presence;
    - int quickness;
    - int reasoning;
    - int selfDisc;
    - int strength;
    - int channeling;
    - int essence;
    - int mentalism;
    - int physical;
    - int endurance;
    - int baseHits;
    - int recoveryMult;
    + getBonusDps();
    + getAgility();
    + getConstitution();
    + getEmpathy();
    + getIntuition();
    + getMemory();
    + getPresence();
    + getQuickness();
    + getReasoning();
    + getSelfDisc();
    + getStrength();
    + getChanneling();
    + getEssence();
    + getMentalism();
    + getPhysical();
    + getEndurance();
    + getBaseHits();
    + getRecoveryMult();
    + getRaceBonus(String statName);
    }
    Class Culture{
    - String cultureName
    - Map <String, Integer> skillMap;
    + getSkillMap();
    }
    Class Profession{}
    Class TalentsAndFlaws{}
    Class Stat{
        - String name
        - int potentional
        - int temp
        # int bonus()
        # int racial()
        # int special()
        # int getTotal()
        # int getPotentional()
        # getTemp()
    }
}

CharacterSheet *-- PrimaryStats
CharacterSheet *-- MME
CharacterSheet *-- Defense
Inventory o-- MagicItems
Inventory o-- GeneralEquipment
CharacterSheet *-- TalentsAndFlaws
CharacterSheet *-- SkillCategory
SkillCategory *-- Skill
CharacterSheet *-- SpellCategory
SpellCategory *-- Spell
CharacterSheet *-- Inventory
CharacterSheet *-- Race
CharacterSheet *-- Culture
CharacterSheet *-- Profession
PrimaryStats *-- Stat


package util {
    Class FileIO{}
    Class TextUI{}
    Class dataLoader{}
    Class parseJson
}

Main *--- RoleMaster
RoleMaster *-- CharacterSheet
RoleMaster *-- views
RoleMaster *-- Dice
RoleMaster *-- util
RoleMaster *-- Rules
@enduml

implements ..|>
extends <|-- (is-a)
composition *-- (must-have)
Aggregation o-- (can-have)
Associering <--