@startuml
'https://plantuml.com/object-diagram
!pragma layout smetana
object Rolemaster
object inventory
object PrimaryStats
object skillList
object spellList
object equipped
object characterInfo
object Race
object profession
object background
object rules
object maneuversMovementAndEncumbrance
object developmentPoints
object talents
object culture
object CharacterSheet
object skillCategories
object dice
object defense
object weaponAttackSetup
object skills
object spells
object magicItems
object armor
object weapon
object level
object xp

Rolemaster o-- CharacterSheet
Rolemaster *-- rules
Rolemaster *-- dice
CharacterSheet *-- PrimaryStats
CharacterSheet *-- skillList
CharacterSheet *-- spellList
CharacterSheet *--- characterInfo
CharacterSheet *-- inventory
characterInfo *-- Race
characterInfo *-- profession
characterInfo *-- background
characterInfo *-- culture
CharacterSheet *-- talents
CharacterSheet *-- defense
inventory o-- equipped
CharacterSheet *-- maneuversMovementAndEncumbrance
CharacterSheet *-- weaponAttackSetup
skillList *-- skillCategories
skillCategories *-- skills
spellList o-- spells
inventory o-- magicItems
equipped o-- armor
equipped o-- weapon
weapon <--> weaponAttackSetup
armor <--> defense
characterInfo *-- level
characterInfo *-- xp
rules *-- developmentPoints

@enduml
extends <|-- (is-a)
composition *-- (must-have)
Aggregation o-- (can-have)
Associering <--