@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant Main
participant User
participant View
participant Controller
participant Model


Main -> View: new
Main -> Model: new
Main -> Controller: new
Main-> Model:new
Controller --> View: Vis start
User -> View: Opret ny
View -> Controller: "Opret ny" tryk
Controller -> Model: Be om race
Model -> Controller
Controller -> View: ""Vis vælg race"
User -> View: valgt "High elf"
View -> Controller: race = High "High elf"
Controller -> Model: setRace(""High elf")
Controller -> Controller: Get cultures
Controller -> View: Vis vælg culture

@enduml